### ISSUE TITLE
Kubos debug command

### ISSUE THREAD

**Issue by kyleparrott** [openkosmosorg/kubos-sdk#34]
This command would flash the program to the board and leave the debugger (mspdebug, openocd, etc.) open for the user to interact.

**Comment by rplauche** [comment]
Would be pretty cool if it could detect binary changes (recompile) and auto reload/reflash.

**Comment by kyleparrott** [comment]
It could also might be useful to auto start a gdb server/gdb instance somehow to give a unified debugging experience instead of having to work directly with openocd/mspdebug
