### ISSUE TITLE
ls command

### ISSUE THREAD

**Issue by rplauche** [openkosmosorg/kubos-sdk#37]
Appears not to show any output. Using kubos-sdk 0.0.2 and container 0.0.2, fedora 24.

**Comment by TheHollidayInn** [comment]
What should the output be?

**Comment by rplauche** [comment]
The `kubos ls` command is just a pass through to the `yotta ls` command. The actual output is just a list of module dependencies for the current module/target combination.

**Comment by rplauche** [comment]
I should note that this command works fine on other systems, there may be something special about my setup.

**Comment by rplauche** [comment]
This issue is a duplicate of #42, closing.
