### ISSUE TITLE
Cleanup new project json

### ISSUE THREAD

**Issue by rplauche** [openkosmosorg/kubos-sdk#41]
Currently when you init a new project the url and homepage are set to the example-kubos-rt project.

**Comment by TheHollidayInn** [comment]
Where are the defaults for the module.json file stored? And, should these values be set using the `following_args`?

**Comment by marshall** [comment]
IIRC we're just copying the `module.json` directly from kubos-rt-example: https://github.com/openkosmosorg/sdk-container-tools/blob/master/kubos-sdk.py#L79

**Comment by rplauche** [comment]
Yea that is correct. Ideally we would either blank out those kubos-rt-example specific values or have the user input new ones as part of the project creation.

**Comment by TheHollidayInn** [comment]
Sweet. I think I have an idea of how to do that. 

On a side note, can you point me to the code that actually copies the module.json file from kubos-rt-example? I am having trouble finding it.

**Comment by rplauche** [comment]
The copy which creates the new project and copies over the existing example code can be found here: https://github.com/openkosmosorg/sdk-container-tools/blob/master/kubos-sdk.py#L79. This issue should probably be moved to the openkosmosorg/sdk-container-tools project.
